---
title: loveyourself
author: Alexander Halbeisen
email: alex.halbeisen@gmail.com
description: For T.
baseurl: "/"
url: loveryourself.fund
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
menu:
  main:
    weight: "3"
    title: More
