---
title: loveyourself
author: Alexander Halbeisen
email: alex.halbeisen@gmail.com
description: For my loved one.
baseurl: "/fortierica"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
